[project]
name = "state-of-the-art-examine-service"
authors = ["State-of-the-Art Innovations"]
description = "Advanced examination and assessment service for digital infrastructure"
telemetry = false
requirements = []
[contracts.assessment-governance]
path = "contracts/assessment-governance.clar"
depends_on = []

[contracts.examination-registry]
path = "contracts/examination-registry.clar"
depends_on = []

[contracts.assessment-metrics]
path = "contracts/assessment-metrics.clar"
depends_on = []

[contracts.evaluation-licensing]
path = "contracts/evaluation-licensing.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
